### ISSUE TITLE
rbac.Permit() does not recurse through parent roles.

### ISSUE THREAD

**Issue by brendesp** [euroteltr/rbac#5]
rbac.IsGranted() does not recurse through parent roles to check for inherited permissions.

**Comment by derkan** [comment]
Hi @brendesp, 
You are right, it is not checking parent roles if any them already got that permission. In my opinion we should let checking if perm exists by calling `rbac.IsGranted(...` to developer. Because some may need same perms on different roles.
 
If you need this, It can be implemented by wrapping  `rbac.Permit()` function  in a new func `rbac.PermitUnique()` which will check first if grant any parent by calling  `rbac.IsGranted(...`  without breaking api. I'll be glad for a pull request.

**Comment by derkan** [comment]
PR is merged, thanks
